### ISSUE TITLE
Styling issues - bootstrap missing?

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/ecan-webappbuilder-components#12]
Button has missing styling .... Maybe bootstrap reference missing?

**Comment by coomsie** [comment]
Add to init.js file ...

```
resources = resources.concat([
  window.apiUrl + 'dojo/resources/dojo.css',
  window.apiUrl + 'dijit/themes/claro/claro.css',
  window.apiUrl + 'esri/css/esri.css',
  window.apiUrl + 'dojox/layout/resources/ResizeHandle.css',
  window.path + 'jimu.js/css/jimu.css',
  'https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js',
  'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css',
  'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'
]);
```

though maybe not he best approach...

**Comment by SamDrummond** [comment]
I might have to update the documentation in master - the css file is actually the only dependancy. 
JQuery and Bootstrap itself are no longer needed. 

I'm more than happy to code something up to do this in the widget itself - however this is how Esri has documented to do it (https://developers.arcgis.com/web-appbuilder/sample-code/add-a-third-party-library.htm) Your call, I'm happy to make the change.

**Comment by SamDrummond** [comment]
Actually I just read to the end of the document. This is the use case if the library is used by many widgets. If it is just a single widget I should be able to:

"If the library is used by one widget only, you can put the library in the widget's folder and add it in the widget's define dependencies array."

**Comment by coomsie** [comment]
Ok sounds good

**Comment by coomsie** [comment]
Sound even better …!

**Comment by coomsie** [comment]
Styling ok, just a re-work of how the libs are inserted .... see above.

**Comment by SamDrummond** [comment]
Resolved in the development branch - will leave open until next release is given to ECAN.
