### ISSUE TITLE
Extents are ignored

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/ecan-webappbuilder-components#14]
http://test.canterburymaps.govt.nz/webapps/wab/?webmap=a0bf3353b73c4bed83d3d87c550a04fa&extent=172.0891,-43.4092,172.3101,-43.3234,

The extent is ignored and the extent is being captured in the wrong place *(well seems incorrect)

**Comment by SamDrummond** [comment]
This is a major bug that needs to be resolved as soon as possible. As discussed on Friday the 1st this release was known to have issues with extents. Ryan and I are investigating the limitations of the [extent URL parameter in the WAB](http://doc.arcgis.com/en/web-appbuilder/manage-apps/app-url-parameters.htm#ESRI_SECTION1_7D207DF919C049D68B7F9E1423962B4E). 

I have put a question on [GeoNet](https://geonet.esri.com/thread/154681) and forwarded it to Scott Bradley from Eagle who confirmed that the WAB does not automatically reproject extents.

Ryan and I discussed exploring whether the URL parameters work at all as he suspected you could only provide one parameter (either an Extent or a WebMapID).  Can someone (Ryan?) please verify that these URL’s work correctly at ECAN? They seem fine on my instance of the WAB:

**VARIATION 3 PLWRP:** 
http://[WABURL]?webmap=120a16c944cd4bd68635266fd57961c8&extent=1546400.2866970366,5146704.542801532,1636755.6757411482,5168863.441285995,2193

**REGIONAL COASTAL ENVIRONMENT PLAN - COASTAL EROSION:**
http://[WABURL]?webmap=98bc5f8a6aed455bb48223dce5f3749d&extent=1513525.7417812797,5221647.921854954,1603881.1308253913,5243806.820339417,2193

**CANTERBURY AIR REGIONAL PLAN:**
http://[WABURL]?webmap=ea9ae61f9e8f4d70a977d869b2c2e527&extent=1425154.731705926,5106950.817460746,1515510.1207500375,5146836.83473278,2193

If these work then my suspicion is that the URL parameters work but only if they are provided in a spatial reference that matches the destination webmap. If this is the case we have the option of returning the web map WKID in the Rest API – if this is feasible from ECAN’s end.

If not we will need to explore preloading the gallery widget and harvesting our own URL parameters.

I will assign this to Ryan as he was the last point of contact I had regarding the URL’s.

**Comment by coomsie** [comment]
I can verify those NZTM cords do work … (if the map is in nztm)

http://test.canterburymaps.govt.nz/webapps/wab/?webmap=ea9ae61f9e8f4d70a977d869b2c2e527&extent=1425154.731705926,5106950.817460746,1515510.1207500375,5146836.83473278,2193#

maybe might need to only allow this to work with nztm?

This works … map not in nztm though ….. in world merc
http://test.canterburymaps.govt.nz/webapps/wab/?webmap=c13165aa37bc4383baf1ef3f1df6697d&extent=172.1071,-43.3503,172.62291,-42.7588,4326#

means it’s tricky as you would need to know what the target is before producing the map with the right coords..

**Comment by SamDrummond** [comment]
Agreed. Ryan was going to look at the feasiblity of scraping the webmap spatial reference with the rest of the parameters in the Portal API. Then we could know the target webmap spatial reference and could do a reproject.

However, I understand from what he has said that this is easier said than done.  Happy to look at other ways though.
