### ISSUE TITLE
Details button - doesnt work

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/ecan-webappbuilder-components#16]
Details button fails to open after search

this occurs on safari / chrome / firefox

![gismo_and_new_issue_ _canterburyregionalcouncil_ecan-webappbuilder-components_and_gismo](https://cloud.githubusercontent.com/assets/125121/7486540/fb5a7e92-f3fa-11e4-9382-dde1cde80cb2.png)

![gismo_and_new_issue_ _canterburyregionalcouncil_ecan-webappbuilder-components_and_archive](https://cloud.githubusercontent.com/assets/125121/7486531/cd4b0a58-f3fa-11e4-844f-4304335f9999.png)

**Comment by SamDrummond** [comment]
Fixed in development branch to be included in the next release.

**Comment by SamDrummond** [comment]
Will leave this open for testing and will keep assigned with me until release is given to ECAN.
