### ISSUE TITLE
Code Attachment Object returning from PortalAPI Request

### ISSUE THREAD

**Issue by SamDrummond** [CanterburyRegionalCouncil/ecan-webappbuilder-components#17]
I've found a small bug with the API. It seem's that in some circmstances that there is an object with a type of "Code Attachment" coming back with the maps and apps. Do a text search for "Code Attachment" through the response from the following request 

http://test.canterburymaps.govt.nz/portalapi/MapGallerySearch?PageSize=6&Page=1&OrderBy=MostRecent

**Comment by coomsie** [comment]
Yes, fixed in prod, but not in test ....

**Comment by pogglethelesser** [comment]
I've now cleared the "Code Attachment" items from the system,
