### ISSUE TITLE
Explore: On load use return button - reloads web page

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/ecan-webappbuilder-components#22]
Explore: On load use return button - reloads web page, this shouldnt happen.

only happens on first load,

**Comment by SamDrummond** [comment]
Just saw this now. Will resolve this morning.

**Comment by SamDrummond** [comment]
This was resolved in https://github.com/CanterburyRegionalCouncil/ecan-webappbuilder-components/commit/37d770f5a1dde3f3e371b164da70da57fc9adc59

Ready for testing.

**Comment by TheFletcher** [comment]
Sorted!
